# ============================================================
# Genus synthesis script for HL5
# ============================================================

source design_knobs.tcl

set_db init_lib_search_path {.}
set_db hdl_search_path [list \
  ./bdw_work/modules/hl5/BASIC \
  ./bdw_work/modules/fedec/BASIC \
  ./bdw_work/modules/execute/BASIC \
  ./bdw_work/modules/memwb/BASIC \
]

# Read RTL generated by Stratus
read_hdl -sv ./bdw_work/modules/fedec/BASIC/fedec_rtl.v
read_hdl -sv ./bdw_work/modules/execute/BASIC/execute_rtl.v
read_hdl -sv ./bdw_work/modules/memwb/BASIC/memwb_rtl.v
read_hdl -sv ./bdw_work/modules/hl5/BASIC/hl5_rtl.v

# Read timing library
read_libs /home/classes/ee/272/mflowgen/adks/freepdk-45nm/view-standard/stdcells.lib

# Elaborate top
elaborate hl5

# Clock constraint
create_clock -name $CLK_PORT -period $CLK_PERIOD [get_ports $CLK_PORT]

# Synthesis effort knobs
set_db syn_generic_effort $SYN_GENERIC_EFFORT
set_db syn_map_effort     $SYN_MAP_EFFORT
set_db syn_opt_effort     $SYN_OPT_EFFORT

# Optional area constraint
if {$MAX_AREA > 0} {
    set_max_area $MAX_AREA
}

# Synthesis flow
syn_generic
syn_map
syn_opt

# Reports
report_area   > genus_area.rpt
report_timing > genus_timing.rpt
report_power  > genus_power.rpt

# Outputs for Innovus
write_hdl > hl5_mapped.v
write_sdc > hl5.sdc
